# Generated by Django 6.0.4 on 2026-05-05 05:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_display_name', models.CharField(blank=True, help_text='Display name shown on cards (mirrors Supabase provider text field)', max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('experience', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('design', 'Design'), ('development', 'Development'), ('writing', 'Writing & Content'), ('marketing', 'Marketing'), ('video', 'Video & Animation'), ('photography', 'Photography'), ('cleaning', 'Cleaning'), ('repairs', 'Repairs'), ('transport', 'Transport'), ('security', 'Security'), ('other', 'Other')], default='other', max_length=30)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('price', models.CharField(blank=True, help_text='e.g. "$50", "₦25,000"', max_length=100)),
                ('per', models.CharField(blank=True, help_text='e.g. "per hour", "per project"', max_length=50)),
                ('is_available', models.BooleanField(default=True)),
                ('rating', models.DecimalField(decimal_places=2, default=5.0, max_digits=3)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(help_text='The freelancer offering this service', on_delete=django.db.models.deletion.CASCADE, related_name='services_offered', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'services_service',
                'ordering': ['-created_at'],
            },
        ),
    ]
