# Generated by Django 6.0.4 on 2026-05-05 05:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('job', 'Job'), ('booking', 'Booking'), ('payment', 'Payment'), ('review', 'Review'), ('promo', 'Promo'), ('system', 'System')], default='system', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications_notification',
                'ordering': ['-created_at'],
            },
        ),
    ]
